#整合springMVC
#tomcat访问路径
server:
  servlet:
    context-path: /web

#整合spring
spring:
  datasource:
    username: root
    password: yz2021
    url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&userUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver

#整合mybatis
mybatis:
  type-aliases-package: com.study.pojo
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml